# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "twentyseventeen4hugo"
license = "GPLv2 or later"
licenselink = "http://www.gnu.org/licenses/gpl-2.0.html"
description = "a partial port of Wordpress Twentyseventeen for Hugo theme"
homepage = "http://ururimi.com/"
tags = [one-column, two-columns, right-sidebar, flexible-header, accessibility-ready, custom-colors, custom-header, custom-menu, custom-logo, editor-style, featured-images, footer-widgets, post-formats, rtl-language-support, sticky-post, theme-options, threaded-comments, translation-ready]
features = [multiple sections on the front page as well as widgets, navigation and social menus, a logo, and more. Personalize its asymmetrical grid with a custom color scheme and showcase your multimedia content with post formats]
min_version = 0.19

[author]
  name = "Patrick Stainier"
  homepage = "http://kioprojects.co"

# If porting an existing theme
[original]
  name = "Twentyseventeen"
  homepage = "https://wordpress.org/themes/twentyseventeen/"
  repo = "https://downloads.wordpress.org/theme/twentyseventeen.1.1.zip"
